// ─── 帮助指南（聊天分段长文） ───
// 文案须与本代命令目录、模式目录实际成员同步维护。

import type { Player } from "@minecraft/server";
import { color, trySendMessage } from "@yinxe/toolkit";

const SECTIONS: string[][] = [
  [
    `${color.bold}${color.accent}≡≡≡ MockPlayer · 功能介绍 ≡≡≡`,
    "",
    `${color.success}mockplayer3 ${color.muted}是一个模拟玩家（假人）管理模组。`,
    `${color.muted}你可以创建假人来协助完成自动化任务。`,
    "",
    `${color.accent}▶ 可共存开关`,
    `${color.muted}  ${color.playerName}自动重生${color.muted}: 死亡后自动复活到重生点`,
    `${color.muted}  ${color.playerName}潜行${color.muted}: 假人保持潜行姿态（同步实体）`,
    `${color.muted}  ${color.playerName}主人下线联动${color.muted}: 主人离开游戏时假人联动下线`,
    "",
    `${color.accent}▶ 工作模式（同一时间只能选一个，互斥）`,
    `${color.muted}  ${color.playerName}空闲${color.muted}: 默认状态，不执行任何行为`,
    `${color.muted}  ${color.playerName}定点挖掘${color.muted}: 自动破坏面前的方块（准星射线 6 格内）`,
    `${color.muted}  ${color.playerName}定点放置${color.muted}: 将手中方块放置到面前位置`,
    `${color.muted}  ${color.playerName}定点攻击${color.muted}: 持续向正前方近战挥击（不动·不转向）`,
    `${color.muted}  ${color.playerName}跟随${color.muted}: 跟随主人的位置与视角`,
    `${color.muted}  ${color.playerName}自动钓鱼${color.muted}: 水体探测+抛竿循环+咬钩收竿`,
    `${color.muted}  ${color.playerName}闲逛${color.muted}: 随机游走探索周围`,
    `${color.muted}  ${color.playerName}劫掠${color.muted}: 原地常驻施加袭击之兆引发袭击，胜利自动结算（启动与每胜各扣一瓶，前置不满足自动落空闲）`,
    `${color.muted}  ${color.playerName}宝库模式${color.muted}: 自动用钥匙开 Trial Chambers 宝库`,
    `${color.muted}  ${color.playerName}资源采集(原木)${color.muted}: 寻点→靠近→逐格采集→吸附掉落→换点（归实现性功能总闸，验收后可用）`,
    "",
    `${color.accent}▶ 宝库模式专有说明`,
    `${color.muted}  开启后假人会尝试用手中的钥匙打开面前的宝库。`,
    `${color.muted}  交互成功后自动重连刷新躯体，绕过每人只能开一次的`,
    `${color.muted}  限制。支持普通钥匙（trial_key）和不详钥匙（ominous_trial_key）。`,
    `${color.muted}  每次开完后向最近玩家报告剩余钥匙数量。`,
    "",
    `${color.accent}▶ 劫掠模式专有说明`,
    `${color.muted}  假人须在村庄范围内原地挂机，袭击由原版引擎生成与推进。`,
    `${color.muted}  袭击生物需由假人击杀才算得胜，本模式不主动攻击，故胜场不保证。`,
    `${color.muted}  因此开启时不作任何播报：只有真正打赢一轮才有一条胜利结算消息。`,
    `${color.muted}  胜利结算：扣一瓶、把村庄英雄叠给主人并从假人身上清除。`,
    "",
  ],
  [
    `${color.bold}${color.accent}≡≡≡ MockPlayer · 快速上手 ≡≡≡`,
    `${color.accent}▶ 创建假人`,
    `${color.muted}  1. 使用 ${color.info}/mp:menu ${color.muted}打开主菜单（或手持信物右键）`,
    `${color.muted}  2. 点击 ${color.success}创建模拟玩家${color.muted}，填写名称和坐标`,
    `${color.muted}  3. 创建后假人自动上线加入世界`,
    "",
    `${color.accent}▶ 管理假人`,
    `${color.muted}  在 ${color.accent}模拟玩家列表 ${color.muted}中点击假人进入管理面板，`,
    `${color.muted}  可进行以下操作：`,
    `${color.muted}  - ${color.highlight}行为菜单 ${color.muted}切换工作模式/开关/跟随`,
    `${color.muted}  - 上下线 / 传送过去 / 同步姿态`,
    `${color.muted}  - 互换背包 / 回收资源 / 丢弃物品 / 改名`,
    `${color.muted}  - 设置重生点 / 投掷三叉戟 / 投掷物认主`,
    `${color.muted}  - 杀死 / 删除假人`,
    "",
    `${color.accent}▶ 长按假人`,
    `${color.muted}  站立长按假人=打开其管理面板；潜行长按=直达行为菜单。`,
    "",
    `${color.accent}▶ 批量上下线`,
    `${color.muted}  在 ${color.gold}在线管理 ${color.muted}中可以批量切换假人的在线状态。`,
    "",
  ],
  [
    `${color.bold}${color.accent}≡≡≡ MockPlayer · 命令参考 ≡≡≡`,
    `${color.info}/mp:menu ${color.muted}- 打开主菜单`,
    `${color.info}/mp:create [名称] [坐标] [维度] ${color.muted}- 直接创建假人`,
    `${color.info}/mp:listbots ${color.muted}- 列出所有假人`,
    `${color.info}/mp:online <假人> ${color.muted}- 上线指定假人`,
    `${color.info}/mp:offline <假人> ${color.muted}- 下线指定假人`,
    `${color.info}/mp:delete <假人> ${color.muted}- 删除指定假人（无确认直通）`,
    `${color.info}/mp:killbot <假人> ${color.muted}- 杀死指定假人`,
    `${color.info}/mp:reconnect <假人> ${color.muted}- 假人重连刷新躯体`,
    `${color.info}/mp:recover <假人> ${color.muted}- 从仓内数据强制恢复`,
    `${color.info}/mp:teleportbot <假人> ${color.muted}- 传送到假人身边`,
    `${color.info}/mp:tphere <假人> ${color.muted}- 将假人传送到身边`,
    `${color.info}/mp:move <假人> [坐标] [nearby] ${color.muted}- 寻路（≤16 格，超限直拒）`,
    `${color.info}/mp:work <假人> [模式id|list] ${color.muted}- 切换工作模式`,
    `${color.info}/mp:follow <假人> [清除] ${color.muted}- 跟随/停止跟随`,
    `${color.info}/mp:sneak <假人> <on|off> ${color.muted}- 潜行开关`,
    `${color.info}/mp:reclaim <假人> ${color.muted}- 回收假人热栏/背包/装备/经验`,
    `${color.info}/mp:respawn <假人> ${color.muted}- 切换自动重生`,
    `${color.info}/mp:setrespawn <假人> ${color.muted}- 设置重生点到你的位置`,
    `${color.info}/mp:trident <假人> ${color.muted}- 打开三叉戟投掷面板`,
    `${color.info}/mp:data <假人> ${color.muted}- 查看假人数据`,
    `${color.info}/mp:storage <假人> ${color.muted}- Storage 绑定调试（管理员）`,
    `${color.info}/mp:admin ${color.muted}- 打开管理员菜单（仅管理员）`,
    `${color.info}/mp:chunkarea add|remove|list ${color.muted}- 常加载区域（管理员）`,
    `${color.info}/mp:cmdlist ${color.muted}- 显示命令目录（本帮助命令版）`,
  ],
  [
    `${color.bold}${color.accent}≡≡≡ MockPlayer · 常见问题 ≡≡≡`,
    `${color.accent}Q: 假人不执行行为？`,
    `${color.muted}A: 检查：①假人在线 ②工作模式已设置且未被全局禁用 ③附近有目标`,
    `${color.muted}  宝库模式还需检查是否手持钥匙`,
    "",
    `${color.accent}Q: 如何让假人自动挖矿？`,
    `${color.muted}A: 在行为菜单中选 ${color.playerName}定点挖掘${color.muted}，假人会破坏面前的方块`,
    "",
    `${color.accent}Q: 宝库模式没反应？`,
    `${color.muted}A: 确保假人主手持有 ${color.playerName}普通钥匙 ${color.muted}或 ${color.playerName}不详钥匙${color.muted}，`,
    `${color.muted}  且面向宝库方块（正面 1~2 格内）`,
    "",
    `${color.accent}Q: 假人死后不见了？`,
    `${color.muted}A: 开启 ${color.playerName}自动重生 ${color.muted}开关，假人死后自动复活`,
    `${color.muted}  未开启则死亡下线，需手动上线`,
    "",
    `${color.accent}Q: 为什么改名要求先下线？`,
    `${color.muted}A: 在线实体的名字只读，在线改名会与记录分裂导致事件错主；`,
    `${color.muted}  下线后改名即刻生效，物品仓数据随记录无需迁移`,
  ],
];

export function showHelpGuide(player: Player): void {
  for (const section of SECTIONS) {
    for (const line of section) trySendMessage(player, line);
  }
}
